name: Build Master Branch

on:
  workflow_call:
    secrets:
      token:
        required: true

  push:
    branches:
      - "master"

jobs:
  build:
    name: Enviroment ${{ matrix.swift }} on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-14]
        swift: ["5.9"]

    steps:
      - name: Checkout Repository
        id: checkout
        uses: actions/checkout@v4
      - name: Cache Swift dependencies
        uses: actions/cache@v4
        with:
          path: .build
          key: ${{ runner.os }}-spm-${{ hashFiles('**/Package.resolved') }}
          restore-keys: |
            ${{ runner.os }}-spm-


      - name: Set Swift Version
        uses: swift-actions/setup-swift@v1
        with:
          swift-version: ${{ matrix.swift }}

      - name: Build
        id: build
        run: swift build
