# This workflow will build a Swift project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-swift

name: Build Project
on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  package_build:
    name: Build With Version Swift ${{ matrix.swift }} on ${{ matrix.os }}
    runs-on: macos-13-xlarge
    strategy:
      matrix:
        os: [macos-13-xlarge]
        swift: ["5.9"]
    steps:
    - uses: swift-actions/setup-swift@v1.25.0
      with:
        swift-version: ${{ matrix.swift }}
    - uses: actions/checkout@v3
    - name: Build
      run: swift build 
    - name: Test
      run: swift test
